#include "stdafx.h"
#include "type_generator.h"
#include "mod_log.h"
#include "module_registry.h"

#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#ifdef _WIN32
#include <direct.h>
#define MKDIR(p) _mkdir(p)
#define PATH_SEP "\\"
#else
#include <sys/stat.h>
#define MKDIR(p) mkdir(p, 0755)
#define PATH_SEP "/"
#endif

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

bool TypeGenerator::EnsureDir(const std::string &dir) {
  if (MKDIR(dir.c_str()) == 0)
    return true;
#ifdef _WIN32
  return (errno == EEXIST);
#else
  return (errno == EEXIST);
#endif
}

bool TypeGenerator::WriteFile(const std::string &filePath,
                              const std::string &content) {
  // Always overwrite — .d.ts files must stay in sync with registered modules.
  FILE *f = fopen(filePath.c_str(), "wb");
  if (!f) {
    ModLog("[types] Failed to open for writing: %s\n", filePath.c_str());
    return false;
  }
  fwrite(content.c_str(), 1, content.size(), f);
  fclose(f);
  return true;
}

static std::string JoinPath(const std::string &a, const std::string &b) {
  if (a.empty())
    return b;
  char last = a.back();
  if (last == '/' || last == '\\')
    return a + b;
  return a + PATH_SEP + b;
}

// ---------------------------------------------------------------------------
// Per-module .d.ts
// ---------------------------------------------------------------------------
void TypeGenerator::GenerateModuleDts(const std::string &outputDir) {
  const auto &defs = ModuleRegistry::GetAll();

  for (const auto &mod : defs) {
    std::ostringstream out;

    out << "// Auto-generated by the engine type system. Do not edit "
           "manually.\n";
    out << "// Regenerated each time the application starts.\n\n";

    if (!mod.description.empty()) {
      out << "/**\n";
      std::istringstream desc(mod.description);
      std::string line;
      while (std::getline(desc, line))
        out << " * " << line << "\n";
      out << " */\n";
    }

    out << "declare module '" << mod.name << "' {\n";

    for (const auto &fn : mod.functions) {
      std::string paramList;
      if (fn.params.empty() && fn.returnType == "void") {
        paramList = "...args: any[]";
      } else {
        bool first = true;
        for (const auto &p : fn.params) {
          if (!first)
            paramList += ", ";
          paramList += p.name + ": " + p.type;
          first = false;
        }
      }

      const std::string ret = fn.returnType.empty() ? "void" : fn.returnType;

      out << "  /**\n";
      out << "   * Bound from C++ (`" << mod.name << "::" << fn.name << "`)\n";
      for (const auto &p : fn.params)
        out << "   * @param " << p.name << " `" << p.type << "`\n";
      out << "   * @returns `" << ret << "`\n";
      out << "   */\n";
      out << "  export function " << fn.name << "(" << paramList << "): " << ret
          << ";\n\n";
    }

    out << "}\n";

  const std::string filePath = JoinPath(outputDir, mod.name + ".d.ts");
  if (WriteFile(filePath, out.str()))
    ModLog("[types] Written: %s\n", filePath.c_str());
  }
}

// ---------------------------------------------------------------------------
// globals.d.ts
//
// Declares each C++ module as a typed ambient global in script context.
//
// typeRoots processes files as scripts (not modules), so we cannot use
// import() types or top-level export {}. Instead we manually redeclare each
// function signature inside a `declare namespace` that matches the module
// name — this gives full typed autocomplete for `engine.log(...)` etc.
// without any import statement in mod source files.
// ---------------------------------------------------------------------------
void TypeGenerator::GenerateGlobalsDts(const std::string &outputDir) {
  const auto &defs = ModuleRegistry::GetAll();
  if (defs.empty())
    return;

  std::ostringstream out;
  out << "// Auto-generated global bindings. Do not edit manually.\n";
  out << "// Regenerated each time the application starts.\n\n";

  // SDK class declarations (global constructors / instance types)
  out << "/** 3D world position. Create with new WorldLocation(x, y, z). Avoids conflict with global Location. */\n";
  out << "declare class WorldLocation {\n";
  out << "  x: number;\n";
  out << "  y: number;\n";
  out << "  z: number;\n";
  out << "  constructor(x: number, y: number, z: number);\n";
  out << "  distanceTo(other: WorldLocation): number;\n";
  out << "}\n\n";

  out << "/** World/level. Returned by Player.getWorld(). */\n";
  out << "declare class World {\n";
  out << "  name: string;\n";
  out << "}\n\n";

  out << "/** Item stack (id 0 = empty). */\n";
  out << "declare class ItemStack {\n";
  out << "  id: number;\n";
  out << "  count: number;\n";
  out << "  auxValue: number;\n";
  out << "}\n\n";

  out << "/** Player inventory: main slots (36), selected hotbar index, armor (4). */\n";
  out << "declare class Inventory {\n";
  out << "  slots: ItemStack[];\n";
  out << "  selectedSlot: number;\n";
  out << "  armor: ItemStack[];\n";
  out << "}\n\n";

  out << "/** Local or remote player. Get via player.get() or player.fromUuid(). */\n";
  out << "declare class Player {\n";
  out << "  name: string;\n";
  out << "  id: number;\n";
  out << "  getWorld(): World;\n";
  out << "  getLocation(): WorldLocation;\n";
  out << "  getHealth(): number;\n";
  out << "  getGameMode(): 'survival' | 'creative' | 'adventure' | 'unknown';\n";
  out << "  getFoodLevel(): number;\n";
  out << "  getSaturation(): number;\n";
  out << "  getExperienceLevel(): number;\n";
  out << "  getTotalExperience(): number;\n";
  out << "  getInventory(): Inventory;\n";
  out << "}\n\n";

  // Strictly typed game events: payload types and event name union for events.on() autocomplete
  out << "/** Event payload types — callback receives these for events.on(eventName, callback). */\n";
  out << "interface PlayerJoinEvent { playerId: number; }\n";
  out << "interface PlayerChatEvent { message: string; playerId: number; }\n";
  out << "interface WorldLoadedEvent { worldName: string; }\n";
  out << "interface TickEvent { }\n";
  out << "interface JoinWorldEvent { playerId: number; worldName: string; }\n\n";
  out << "type GameEventName = 'player_join' | 'player_chat' | 'world_loaded' | 'tick' | 'join_world';\n\n";

  for (const auto &mod : defs) {
    // WorldLocation is exposed as the global class above, not as a namespace
    if (mod.name == "WorldLocation")
      continue;

    // events namespace: strictly typed on() overloads + onJoinWorld(player, world) => void
    if (mod.name == "events") {
      out << "declare namespace events {\n";
      out << "  function on(eventName: 'player_join', callback: (data: PlayerJoinEvent) => void): void;\n";
      out << "  function on(eventName: 'player_chat', callback: (data: PlayerChatEvent) => void): void;\n";
      out << "  function on(eventName: 'world_loaded', callback: (data: WorldLoadedEvent) => void): void;\n";
      out << "  function on(eventName: 'tick', callback: (data: TickEvent) => void): void;\n";
      out << "  function on(eventName: 'join_world', callback: (data: JoinWorldEvent) => void): void;\n";
      out << "  function on(eventName: GameEventName, callback: (data: unknown) => void): void;\n";
      out << "  /** Subscribe to join_world with (player, world) callback. */\n";
      out << "  function onJoinWorld(callback: (player: Player, world: World) => void): void;\n";
      out << "  function _tick(): void;\n";
      out << "}\n\n";
      continue;
    }

    if (!mod.description.empty()) {
      out << "/** " << mod.description << " */\n";
    }
    out << "declare namespace " << mod.name << " {\n";

    for (const auto &fn : mod.functions) {
      std::string paramList;
      if (fn.params.empty() && fn.returnType == "void") {
        paramList = "...args: any[]";
      } else {
        bool first = true;
        for (const auto &p : fn.params) {
          if (!first)
            paramList += ", ";
          paramList += p.name + ": " + p.type;
          first = false;
        }
      }
      const std::string ret = fn.returnType.empty() ? "void" : fn.returnType;

      out << "  /**\n";
      out << "   * Bound from C++ (`" << mod.name << "::" << fn.name << "`)\n";
      for (const auto &p : fn.params)
        out << "   * @param " << p.name << " `" << p.type << "`\n";
      out << "   * @returns `" << ret << "`\n";
      out << "   */\n";
      out << "  function " << fn.name << "(" << paramList << "): " << ret
          << ";\n\n";
    }

    out << "}\n\n";
  }

  const std::string filePath = JoinPath(outputDir, "globals.d.ts");
  if (WriteFile(filePath, out.str()))
    ModLog("[types] Written: %s\n", filePath.c_str());
}

// ---------------------------------------------------------------------------
// mods/tsconfig.json
//
// Written only if not already present so developers can customise it freely.
// Uses "typeRoots" pointing at our types/ directory so TypeScript picks up
// globals.d.ts automatically for every file in the project — no explicit
// import or reference needed in mod scripts.
// ---------------------------------------------------------------------------
void TypeGenerator::GenerateTsConfig(const std::string &modsDir,
                                     const std::string &typesRelPath) {
  const std::string tsconfigPath = JoinPath(modsDir, "tsconfig.json");

  {
    FILE *f = fopen(tsconfigPath.c_str(), "r");
    if (f) {
      fclose(f);
      ModLog("[types] tsconfig.json already exists — skipping\n");
      return;
    }
  }

  // Valid JSON only — no comments, no duplicate entries.
  std::ostringstream out;
  out << "{\n";
  out << "  \"compilerOptions\": {\n";
  out << "    \"target\": \"ES2020\",\n";
  out << "    \"module\": \"CommonJS\",\n";
  out << "    \"moduleResolution\": \"node\",\n";
  out << "    \"strict\": true,\n";
  out << "    \"esModuleInterop\": true,\n";
  out << "    \"skipLibCheck\": true,\n";
  out << "    \"outDir\": \"./dist\",\n";
  out << "    \"rootDir\": \".\",\n";
  out << "    \"types\": [\"node\"],\n";
  out << "    \"typeRoots\": [\"./node_modules/@types\", "
         "\"../node_modules/@types\", \""
      << typesRelPath << "\"]\n";
  out << "  },\n";
  out << "  \"include\": [\n";
  out << "    \"./**/*.ts\",\n";
  out << "    \"" << typesRelPath << "/**/*.d.ts\"\n";
  out << "  ],\n";
  out << "  \"exclude\": [\n";
  out << "    \"node_modules\",\n";
  out << "    \"dist\"\n";
  out << "  ]\n";
  out << "}\n";

  if (WriteFile(tsconfigPath, out.str()))
    ModLog("[types] Written: %s\n", tsconfigPath.c_str());
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------
void TypeGenerator::Generate(const std::string &outputDir,
                             const std::string &modsDir) {
  ModLog("[types] Generating type declarations...\n");

  if (!EnsureDir(outputDir)) {
    ModLog("[types] Warning: could not create output dir: %s\n",
           outputDir.c_str());
    return;
  }

  if (!EnsureDir(modsDir)) {
    // mods dir might not exist yet — not fatal, tsconfig write will just fail
    ModLog("[types] Note: mods dir does not exist yet: %s\n",
           modsDir.c_str());
  }

  GenerateModuleDts(outputDir);
  GenerateGlobalsDts(outputDir);

  // typesRelPath is the path from modsDir to outputDir.
  // If both are siblings (mods/ and types/ next to exe), it's "../types".
  GenerateTsConfig(modsDir, "../types");

  ModLog("[types] Done\n");
}